In [1]:
import cv2
import numpy as np

In [9]:
img = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
imgF1 = np.fft.fft2(img)
imgF2 = np.fft.fft2(img, (5, 4))

print ('img= \n{}\n'.format(img))
print ('imgF1= \n{}\n'.format(imgF1))
print ('imgF2= \n{}'.format(imgF2))

img= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

imgF1= 
[[ 45. +0.j          -4.5+2.59807621j  -4.5-2.59807621j]
 [-13.5+7.79422863j   0. +0.j           0. +0.j        ]
 [-13.5-7.79422863j   0. +0.j           0. +0.j        ]]

imgF2= 
[[ 45.         +0.j          -6.        -15.j
   15.         +0.j          -6.        +15.j        ]
 [ -8.78115295-28.3726938j  -10.4575646  +6.00473452j
   -2.92705098 -9.4575646j    8.4575646  +0.15063255j]
 [  1.28115295+14.00857761j   3.66952587 -1.15359351j
    0.42705098 +4.66952587j  -5.66952587 -0.29949154j]
 [  1.28115295-14.00857761j  -5.66952587 +0.29949154j
    0.42705098 -4.66952587j   3.66952587 +1.15359351j]
 [ -8.78115295+28.3726938j    8.4575646  -0.15063255j
   -2.92705098 +9.4575646j  -10.4575646  -6.00473452j]]
